-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE CRICKET_DWH WITH WAREHOUSE_SIZE = 'MEDIUM' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 1 SCALING_POLICY = 'STANDARD';

USE ROLE USERADMIN;
CREATE OR REPLACE USER CRICKET_USER PASSWORD = 'TEST@1234' COMMENT = 'THIS USER IS CREATED TO USE SNOWPARK' DEFAULT_ROLE = SYSADMIN DEFAULT_SECONDARY_ROLES = ('ALL') MUST_CHANGE_PASSWORD = FALSE;

USE ROLE SECURITYADMIN;
GRANT ROLE SYSADMIN TO USER CRICKET_USER;
GRANT USAGE ON WAREHOUSE CRICKET_DWH TO ROLE SYSADMIN;