-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE CRICKET;
-- USE SCHEMA --
USE SCHEMA CONSUMPTION;

TRUNCATE TABLE CRICKET.CONSUMPTION.PLAYER_DIM;
INSERT INTO CRICKET.CONSUMPTION.PLAYER_DIM(TEAM_ID,PLAYER_NAME)
SELECT 
DISTINCT 
PD.TEAM_ID AS TEAM_ID,
PD.PLAYER_NAME AS PLAYER_NAME
FROM
(SELECT DISTINCT 
TD.TEAM_ID AS TEAM_ID,
PCT.PLAYER_NAME AS PLAYER_NAME
FROM CRICKET.CLEAN.PLAYER_CLEAN_TBL PCT INNER JOIN CONSUMPTION.TEAM_DIM TD
ON PCT.COUNTRY = TD.TEAM_NAME ORDER BY TD.TEAM_ID, PLAYER_NAME) PD;
