-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE CRICKET;
-- USE SCHEMA --
USE SCHEMA CONSUMPTION;

CREATE OR REPLACE TRANSIENT TABLE CALENDAR_DATES AS
SELECT
    DATEADD(DAY, SEQ4(), '2000-01-01') AS DATE
FROM TABLE(GENERATOR(ROWCOUNT => 11323 + 1))
ORDER BY DATE;

CREATE OR REPLACE TABLE DATE_DIM (DATE_ID, FULL_DT, DAY, MONTH, YEAR, QUARTER, DAYOFWEEK, DAYOFMONTH, DAYOFYEAR, DAYOFWEEKNAME, ISWEEKEND)
AS
SELECT 
    ROW_NUMBER() OVER(ORDER BY DATE) AS DATE_ID,
    DATE AS FULL_DT,
    EXTRACT(DAY FROM DATE) AS DAY,
    EXTRACT(MONTH FROM DATE) AS MONTH,
    EXTRACT(YEAR FROM DATE) AS YEAR,
    EXTRACT(QUARTER FROM DATE) AS QUARTER,
    DAYOFWEEKISO(DATE) AS DAYOFWEEK,
    EXTRACT(DAY FROM DATE) AS DAYOFMONTH,
    DAYOFYEAR(DATE) AS DAYOFYEAR,
    DAYNAME(DATE) AS DAYOFWEEKNAME,
    CASE WHEN UPPER(DAYNAME(DATE)) IN ('SAT','SUN') THEN 1 ELSE 0 END AS ISWEEKEND
FROM CRICKET.CONSUMPTION.CALENDAR_DATES;





