-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE CRICKET;
-- USE SCHEMA --
USE SCHEMA RAW;
-- CREATE TRANSIENT TABLE --
CREATE OR REPLACE TRANSIENT TABLE MATCH_RAW_TBL
(
    META OBJECT NOT NULL,
    INFO VARIANT NOT NULL,
    INNINGS ARRAY NOT NULL,
    STG_FILE_NAME TEXT NOT NULL,
    STG_FILE_ROW_NUMBER INT NOT NULL,
    STG_FILE_CONTENT_KEY TEXT NOT NULL,
    STG_MODIFIED_TS TIMESTAMP NOT NULL
)
COMMENT = 'THIS IS THE RAW TABLE TO STORE ALL THE JSON DATA FILE WITH ROOT ELEMENTS'
;