-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE CRICKET;
-- USE SCHEMA --
USE SCHEMA CONSUMPTION;

TRUNCATE TABLE CRICKET.CONSUMPTION.TEAM_DIM;
INSERT INTO CRICKET.CONSUMPTION.TEAM_DIM 
SELECT DISTINCT ROW_NUMBER() OVER(ORDER BY TEAM_NAME) AS TEAM_ID, TEAM_NAME AS TEAM_NAME
FROM (
SELECT DISTINCT FIRST_TEAM AS TEAM_NAME FROM CLEAN.MATCH_DETAIL_CLEAN
UNION
SELECT DISTINCT SECOND_TEAM AS TEAM_NAME FROM CLEAN.MATCH_DETAIL_CLEAN
) ORDER BY TEAM_NAME;

