-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE CRICKET;
-- USE SCHEMA --
USE SCHEMA CLEAN;
-- CREATE TRANSIENT TABLE --
CREATE OR REPLACE TRANSIENT TABLE CRICKET.CLEAN.PLAYER_CLEAN_TBL AS
SELECT RAW.info:match_type_number::INT AS MATCH_TYPE_NUMBER,
    F.PATH::TEXT AS COUNTRY,
    TEAM.VALUE::TEXT AS PLAYER_NAME,
    STG_FILE_NAME,
    STG_FILE_ROW_NUMBER,
    STG_FILE_CONTENT_KEY,
    STG_MODIFIED_TS
FROM CRICKET.RAW.MATCH_RAW_TBL RAW,
    LATERAL FLATTEN(input => RAW.info:players) F,
    LATERAL FLATTEN(input => F.value) TEAM;