-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE CRICKET;
-- USE SCHEMA --
USE SCHEMA LAND;

-- CREATE JSON FILE FORMAT --
CREATE OR REPLACE FILE FORMAT JSON_FORMAT
    TYPE = JSON 
    NULL_IF = ('\N', 'NULL', 'NUL', '')
    STRIP_OUTER_ARRAY = TRUE
    comment = 'json file format'

-- Create internal named stage --
CREATE OR REPLACE STAGE CRICKET_STG;
