-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE CRICKET;
-- USE SCHEMA --
USE SCHEMA CONSUMPTION;

TRUNCATE TABLE CRICKET.CONSUMPTION.MATCH_FACT;
INSERT INTO CRICKET.CONSUMPTION.MATCH_FACT(MATCH_ID, DATE_ID, REFEREE_ID, TEAM_A_ID, TEAM_B_ID, MATCH_TYPE_ID, VENUE_ID, TOTAL_OVERS, BALLS_PER_OVER, OVERS_PLAYED_BY_TEAM_A, BOWLS_PLAYED_BY_TEAM_A, EXTRA_BOWLS_PLAYED_BY_TEAM_A, EXTRA_RUNS_SCORED_BY_TEAM_A, FOURS_BY_TEAM_A, SIXES_BY_TEAM_A, TOTAL_SCORE_BY_TEAM_A, WICKET_LOST_BY_TEAM_A, OVERS_PLAYED_BY_TEAM_B, BOWLS_PLAYED_BY_TEAM_B, EXTRA_BOWLS_PLAYED_BY_TEAM_B, EXTRA_RUNS_SCORED_BY_TEAM_B, FOURS_BY_TEAM_B, SIXES_BY_TEAM_B, TOTAL_SCORE_BY_TEAM_B, WICKET_LOST_BY_TEAM_B, TOSS_WINNER_TEAM_ID, TOSS_DECISION, MATCH_RESULT, WINNER_TEAM_ID)
SELECT 
    M.MATCH_TYPE_NUMBER AS MATCH_ID,
    DD.DATE_ID AS DATE_ID,
    0 AS REFEREE_ID,
    FTD.TEAM_ID AS FIRST_TEAM_ID,
    STD.TEAM_ID AS SECOND_TEAM_ID,
    MTD.MATCH_TYPE_ID AS MATCH_TYPE_ID,
    VD.VENUE_ID AS VENUE_ID,
    50 AS TOTAL_OVERS,
    6 AS BALLS_PER_OVERS,
    MAX(CASE WHEN D.TEAM_NAME = M.FIRST_TEAM THEN  D.OVER ELSE 0 END ) AS OVERS_PLAYED_BY_TEAM_A,
    SUM(CASE WHEN D.TEAM_NAME = M.FIRST_TEAM THEN  1 ELSE 0 END ) AS BALLS_PLAYED_BY_TEAM_A,
    SUM(CASE WHEN D.TEAM_NAME = M.FIRST_TEAM THEN  D.EXTRAS ELSE 0 END ) AS EXTRA_BALLS_PLAYED_BY_TEAM_A,
    SUM(CASE WHEN D.TEAM_NAME = M.FIRST_TEAM THEN  D.EXTRAS ELSE 0 END ) AS EXTRA_RUNS_SCORED_BY_TEAM_A,
    0 FOURS_BY_TEAM_A,
    0 SIXES_BY_TEAM_A,
    (SUM(CASE WHEN D.TEAM_NAME = M.FIRST_TEAM THEN  D.RUNS ELSE 0 END ) + SUM(CASE WHEN D.TEAM_NAME = M.FIRST_TEAM THEN  D.EXTRAS ELSE 0 END ) ) AS TOTAL_RUNS_SCORED_BY_TEAM_A,
    SUM(CASE WHEN D.TEAM_NAME = M.FIRST_TEAM AND PLAYER_OUT IS NOT NULL THEN  1 ELSE 0 END ) AS WICKET_LOST_BY_TEAM_A,    
    
    MAX(CASE WHEN D.TEAM_NAME = M.SECOND_TEAM THEN  D.OVER ELSE 0 END ) AS OVERS_PLAYED_BY_TEAM_B,
    SUM(CASE WHEN D.TEAM_NAME = M.SECOND_TEAM THEN  1 ELSE 0 END ) AS BALLS_PLAYED_BY_TEAM_B,
    SUM(CASE WHEN D.TEAM_NAME = M.SECOND_TEAM THEN  D.EXTRAS ELSE 0 END ) AS EXTRA_BALLS_PLAYED_BY_TEAM_B,
    SUM(CASE WHEN D.TEAM_NAME = M.SECOND_TEAM THEN  D.EXTRAS ELSE 0 END ) AS EXTRA_RUNS_SCORED_BY_TEAM_B,
    0 FOURS_BY_TEAM_B,
    0 SIXES_BY_TEAM_B,
    (SUM(CASE WHEN D.TEAM_NAME = M.SECOND_TEAM THEN  D.RUNS ELSE 0 END ) + SUM(CASE WHEN D.TEAM_NAME = M.SECOND_TEAM THEN  D.EXTRAS ELSE 0 END ) ) AS TOTAL_RUNS_SCORED_BY_TEAM_B,
    SUM(CASE WHEN D.TEAM_NAME = M.SECOND_TEAM AND PLAYER_OUT IS NOT NULL THEN  1 ELSE 0 END ) AS WICKET_LOST_BY_TEAM_B,
    TW.TEAM_ID AS TOSS_WINNER_TEAM_ID,
    M.TOSS_DECISION AS TOSS_DECISION,
    M.MATACH_RESULT AS MATACH_RESULT,
    MW.TEAM_ID AS WINNER_TEAM_ID
     
FROM 
    CRICKET.CLEAN.MATCH_DETAIL_CLEAN M
    JOIN DATE_DIM DD ON M.EVENT_DATE = DD.FULL_DT
    JOIN TEAM_DIM FTD ON M.FIRST_TEAM = FTD.TEAM_NAME 
    JOIN TEAM_DIM STD ON M.SECOND_TEAM = STD.TEAM_NAME 
    JOIN MATCH_TYPE_DIM MTD ON M.MATCH_TYPE = MTD.MATCH_TYPE
    JOIN VENUE_DIM VD ON M.VENUE = VD.VENUE_NAME AND M.CITY = VD.CITY
    JOIN CRICKET.CLEAN.DELIVERY_CLEAN_TBL D  ON D.MATCH_TYPE_NUMBER = M.MATCH_TYPE_NUMBER 
    JOIN TEAM_DIM TW ON M.TOSS_WINNER = TW.TEAM_NAME 
    JOIN TEAM_DIM MW ON M.WINNER= MW.TEAM_NAME 
    GROUP BY
        M.MATCH_TYPE_NUMBER,
        DATE_ID,
        REFEREE_ID,
        FIRST_TEAM_ID,
        SECOND_TEAM_ID,
        MATCH_TYPE_ID,
        VENUE_ID,
        TOTAL_OVERS,
        TOSS_WINNER_TEAM_ID,
        TOSS_DECISION,
        MATACH_RESULT,
        WINNER_TEAM_ID;