-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE CRICKET;
-- USE SCHEMA --
USE SCHEMA CONSUMPTION;

TRUNCATE TABLE CRICKET.CONSUMPTION.MATCH_TYPE_DIM;
INSERT INTO CRICKET.CONSUMPTION.MATCH_TYPE_DIM(MATCH_TYPE)
SELECT DISTINCT MATCH_TYPE FROM CLEAN.MATCH_DETAIL_CLEAN;