-- USE SYSADMIN ROLE TO CREATE OBJECTS --
USE ROLE SYSADMIN;
-- USE DATABASE --
USE DATABASE CRICKET;
-- USE SCHEMA --
USE SCHEMA CLEAN;
-- CREATE TRANSIENT TABLE --
CREATE OR REPLACE TRANSIENT TABLE CRICKET.CLEAN.DELIVERY_CLEAN_TBL AS
SELECT 
    RAW.INFO:MATCH_TYPE_NUMBER::INT AS MATCH_TYPE_NUMBER,   
    I.VALUE:TEAM::TEXT AS COUNTRY,
    O.VALUE:OVER::TEXT AS OVERS,
    D.VALUE:BOWLER::TEXT AS BOWLER,
    D.VALUE:BATTER::TEXT AS BATTER,
    D.VALUE:NON_STRIKER::TEXT AS NON_STRIKER,
    D.VALUE:RUNS:BATTER::INT AS RUNS,
    D.VALUE:RUNS:EXTRAS::INT AS EXTRAS,
    D.VALUE:RUNS:TOTAL::INT AS TOTAL,
    W.VALUE:PLAYER_OUT::TEXT AS PLAYER_OUT,
    W.VALUE:KIND::TEXT AS PLAYER_OUT_KIND,
    W.VALUE:FIELDERS::VARIANT AS FIELDERS,
    -- O.OVERS:OVER:VALUE:OVER::INT AS OVER,
    RAW.STG_FILE_NAME,
    RAW.STG_FILE_ROW_NUMBER,
    RAW.STG_FILE_CONTENT_KEY,
    RAW.STG_MODIFIED_TS
FROM
CRICKET.RAW.MATCH_RAW_TBL RAW,
LATERAL FLATTEN(INPUT => RAW.INNINGS) I,
LATERAL FLATTEN(INPUT => I.VALUE:OVERS) O,
LATERAL FLATTEN(INPUT => O.VALUE:DELIVERIES) D,
LATERAL FLATTEN(INPUT => D.VALUE:WICKETS, OUTER => TRUE) W